export const authActionsType = {
    REQUEST_SIGNUP:'REQUIRE_SIGNUP',
    SIGNUP_FAILURE:'SIGNUP_FAILURE',

    REQUEST_LOGIN:'REQUIRE_LOGIN',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',

    REQUEST_LOGOUT:'REQUEST_LOGOUT',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE',
};

export const recipeActionsType = {
    REQUEST_RECIPES:'REQUEST_RECIPES',
    LOAD_RECIPES_SUCCESS:'LOAD_RECIPES_SUCCESS',
    LOAD_RECIPES_FAIL:'LOAD_RECIPES_FAIL',

    REQUEST_ADD_RECIPE: 'REQUEST_ADD_RECIPE',
    ADD_RECIPE_SUCCESS:'ADD_RECIPE_SUCCESS',
    ADD_RECIPE_FAIL:'ADD_RECIPE_FAIL',

    REQUEST_RECIPE:'REQUEST_RECIPE',
    LOAD_RECIPE_SUCCESS:'LOAD_RECIPE_SUCCESS',
    LOAD_RECIPE_FAIL:'LOAD_RECIPE_FAIL',

    REQUEST_RECIPE_UPDATE:'REQUEST_RECIPE_UPDATE',
    UPDATE_RECIPE_SUCCESS:'UPDATE_RECIPE_SUCCESS',
    UPDATE_RECIPE_FAIL:'UPDATE_RECIPE_FAIL',

    REQUEST_RECIPE_DELETE:'REQUEST_RECIPE_DELETE',
    DELETE_RECIPE_SUCCESS:'DELETE_RECIPE_SUCCESS',
    DELETE_RECIPE_FAIL:'DELETE_RECIPE_FAIL',


};